openapi: 3.0.0
info:
  title: Crucial MCP Canvas API
  version: 0.1.0
  description: OpenAPI specification for Crucial's LLM-compatible MCP drawing API.
paths:
  /canvas:
    post:
      summary: MCP-style action dispatcher
      description: Dispatches canvas actions based on action name and parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                params:
                  type: object
              required:
              - action
              - params
      responses:
        '200':
          description: Action processed successfully
          content:
            application/json:
              schema:
                type: object
  /canvas/create:
    post:
      summary: Create a new canvas
      description: Creates a new canvas instance and returns the canvas ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                x:
                  type: integer
                y:
                  type: integer
                color:
                  type: string
              required:
              - name
              - x
              - y
              - color
      responses:
        '200':
          description: Canvas created
          content:
            application/json:
              schema:
                type: object
  /mcp/registry:
    get:
      summary: Get MCP-compatible tool registry
      responses:
        '200':
          description: Tool definitions in MCP format
          content:
            application/json:
              schema:
                type: object
